#!/bin/bash
#Place in /etc/init.d and symbolically linke to /etc/rc5.d to run under init5

#go to maschine status script directory and run them
cd #absolute path to htmlout.sh 
./htmout.sh 1>log 2>errors &
echo $! >ols_status.pid

#status code 0 for a succesful exit
exit 0
